# Generated by Django 5.1.1 on 2025-04-08 15:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("QuoraLiteApp", "0002_remove_answer_likes_likes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="likes",
            constraint=models.UniqueConstraint(
                fields=("user", "answer"), name="unique_user_answer_like"
            ),
        ),
    ]
